api_version = "2026-04"
uid = "4dcfcb73-fcd3-9635-eac5-9a0da4fca4909ed8837d"

[[extensions]]
type = "theme"
name = "Miko Rental Calendar"
handle = "miko-rental-calendar"

[extensions.targeting]
  [[extensions.targeting.target]]
  target = "section"
